name: 更新白嫖IP库
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,16 * * *'  # 每天的8点、16点执行（UTC时间）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v2

      - name: Install mmdb-bin
        run: sudo apt install mmdb-bin -y

      - name: 下载并处理IP文件
        run: |
          # 下载zip文件
          wget https://zip.baipiao.eu.org -O ip.zip
          
          # 创建baipiao目录并解压
          mkdir -p baipiao
          unzip ip.zip -d baipiao
          
          > ip_list.txt
          
          # 处理443端口的IP文件
          for file in baipiao/*-443.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:443/' "$file" >> ip_list.txt
            fi
          done
          
          # 处理2053端口的IP文件
          for file in baipiao/*-2053.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:2053/' "$file" >> ip_list.txt
            fi
          done
          
          # 处理2083端口的IP文件
          for file in baipiao/*-2083.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:2083/' "$file" >> ip_list.txt
            fi
          done
          
          # 处理2087端口的IP文件
          for file in baipiao/*-2087.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:2087/' "$file" >> ip_list.txt
            fi
          done
          
          # 处理2096端口的IP文件
          for file in baipiao/*-2096.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:2096/' "$file" >> ip_list.txt
            fi
          done
          
          # 处理8443端口的IP文件
          for file in baipiao/*-8443.txt; do
            if [ -f "$file" ]; then
              sed 's/$/&:8443/' "$file" >> ip_list.txt
            fi
          done

      - name: 识别IP地址的国家代码
        run: |
          > baipiao.txt
          while IFS= read -r line
          do
            ip=$(echo "$line" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            country_code=$(mmdblookup --file GeoLite2-Country.mmdb --ip "$ip" country iso_code | awk -F'"' '{print $2}' | tr -d '\n')
            echo "$line#$country_code" >> baipiao.txt
          done < ip_list.txt

      - name: 提交更新的IP库文件
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 检查文件是否有变化
          if git diff --quiet baipiao.txt; then
            echo "baipiao.txt 文件没有变化，跳过提交"
          else
            echo "检测到 baipiao.txt 文件有变化，开始提交"
            git add baipiao.txt
            git commit -m "更新IP库文件"
            git push
          fi